server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/team6
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    servlet:
      path: /
  application:
    name: service-provider
mybatis:
  type-aliases-package: cn.itcast.service.pojo
logging:
  level:
    cn.itcast: debug
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka