server:
  port: 10010 #服务端口
spring:
  application:
    name: api-gateway #指定服务名
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  routes:
    service-provider: /service-provider/**
    service-consumer: /service-consumer/**
  prefix: /api
#    service-provider: # 这里是路由id，随意写
#      path: /service-provider/** # 这里是映射路径
#      serviceId: service-provider # 指定服务名称
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 # 设置hystrix的超时时间为6000ms